# docker-compose.prod.yml
version: '3.8'

services:
  frontend:
    restart: always
    environment:
      - NODE_ENV=production

  backend:
    restart: always
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  postgres:
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G

  redis:
    restart: always
    command: redis-server --appendonly yes

  nginx:
    restart: always
